<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ProfilerStudy</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <GenerateSupportedOSPlatformAttribute>true</GenerateSupportedOSPlatformAttribute>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
    <GenerateResourceWarnOnBinaryFormatterUse>false</GenerateResourceWarnOnBinaryFormatterUse>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RootNamespace />
    <StartupObject>FramePro.Program</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="app.ico" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CanvasDataGrid\CanvasDataGrid.csproj" />
    <ProjectReference Include="..\CoreUtils\CoreUtils.csproj" />
    <ProjectReference Include="..\docker\Docker.csproj" />
    <ProjectReference Include="..\ProfilerCanvas\ProfilerCanvas.csproj" />
    <ProjectReference Include="..\ProfilerStudyCore\ProfilerStudyCore.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Resources\" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Profiler_GameSimulator.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiler_RecordingPlayer.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="VisualStudioOpenFileAndLine.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="open_source.sh">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="open_source_clion.sh">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="open_source_vscode.sh">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions" Version="8.0.0" />
  </ItemGroup>
</Project>
