<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>ProfilerStudy.McpServer</AssemblyName>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>11.0</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ProfilerStudyCore\ProfilerStudyCore.csproj" />
    <ProjectReference Include="..\CoreUtils\CoreUtils.csproj" />
  </ItemGroup>
</Project>
