<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>FramePro</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net8.0-windows</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RootNamespace />
    <StartupObject>FramePro.Program</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\docker\docker.csproj" />
    <ProjectReference Include="..\Editor\Editor.csproj" />
    <ProjectReference Include="..\FrameProCore\FrameProCore.csproj" />
    <ProjectReference Include="..\HDataGrid\HDataGrid.csproj" />
    <ProjectReference Include="..\SCLCoreCLR\SCLCoreCLR.csproj" />
  </ItemGroup>
</Project>